#!/usr/bin/env bash
# k8s-print-join-command.sh — wrapper used as the SSH forced-command for the
# auto-join key on the master.  Behaviour:
#
#   1. If the worker passed a hostname as the SSH command argument
#      (sshd exposes it as $SSH_ORIGINAL_COMMAND even when a forced
#      command is set), and the hostname matches the expected pattern,
#      delete any existing Node object with that name.  This lets us
#      reimage a worker without leaving behind a stale "NotReady" /
#      "SchedulingDisabled" Node on the master.
#
#   2. Print a fresh join command.
#
# Runs as the "kube" user (the SSH login user).  Errors from kubectl are
# logged to stderr but never block the join — worst case the operator
# still has to run `kubectl delete node <name>` manually.

set -euo pipefail

KUBECONFIG="${KUBECONFIG:-/home/kube/.kube/config}"
LOG_TAG="k8s-print-join-command"

requested="${SSH_ORIGINAL_COMMAND:-}"

# Strict allow-list: hostnames generated by this project look like
# "k8s-node-<6-hex-chars>".  Refuse anything else to avoid arbitrary
# kubectl delete on operator-named nodes (control plane, etc.).
if [[ "$requested" =~ ^k8s-node-[a-f0-9]{6}$ ]]; then
  if kubectl --kubeconfig="$KUBECONFIG" get node "$requested" >/dev/null 2>&1; then
    echo "[$LOG_TAG] deleting stale node object: $requested" >&2
    kubectl --kubeconfig="$KUBECONFIG" delete node "$requested" \
      --ignore-not-found --wait=false >&2 || \
      echo "[$LOG_TAG] WARN: kubectl delete node $requested failed" >&2
  fi
elif [[ -n "$requested" ]]; then
  echo "[$LOG_TAG] WARN: ignoring unexpected SSH_ORIGINAL_COMMAND: $requested" >&2
fi

exec kubeadm token create --print-join-command
